// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQtrfgMu5tSS5OZhwa43biAc6rfHnSmfU',
    appId: '1:595471223494:web:38a29f1f1a84811f8ae5c7',
    messagingSenderId: '595471223494',
    projectId: 'admincarwashepd',
    authDomain: 'admincarwashepd.firebaseapp.com',
    storageBucket: 'admincarwashepd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjGdFna3O4DOLXkAribmajjzMRWs1iBXE',
    appId: '1:595471223494:android:f7d03548d75a88848ae5c7',
    messagingSenderId: '595471223494',
    projectId: 'admincarwashepd',
    storageBucket: 'admincarwashepd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQtrfgMu5tSS5OZhwa43biAc6rfHnSmfU',
    appId: '1:595471223494:web:aa5e85d43e7d46f88ae5c7',
    messagingSenderId: '595471223494',
    projectId: 'admincarwashepd',
    authDomain: 'admincarwashepd.firebaseapp.com',
    storageBucket: 'admincarwashepd.firebasestorage.app',
  );
}
